server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    name: ordering_system
    url: jdbc:mysql://localhost:3306/ordering_system?serverTimezone=UTC
    username: root
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.htl.entity

